[book]
authors = ["Edwin Solares"]
language = "en"
multilingual = false
src = "src"
title = "UCSD CSE151A Summer Session I 2024"

[output.html.playground]
runnable = false

[preprocessor.pagetoc]
[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js  = ["theme/pagetoc.js"]
